//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkup
    {
        public int Checkup_id { get; set; }
        public System.DateTime Checkup_date { get; set; }
        public int Id_equipment { get; set; }
        public string Description { get; set; }
        public string Result { get; set; }
        public int Id_employee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
